// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");

function divisible(x) {
  if (x % 3 === 0) {
    return /* true */1;
  } else {
    return +(x % 5 === 0);
  }
}

var myList = List.filter(divisible)($$Array.to_list($$Array.init(999, (function (i) {
                return i + 1 | 0;
              }))));

var mySum = List.fold_right((function (x, y) {
        return x + y | 0;
      }), myList, 0);

console.log(mySum);

exports.divisible = divisible;
exports.myList = myList;
exports.mySum = mySum;
/* myList Not a pure module */
