// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function fib(prev, curr, sum, limit) {
  var next = prev + curr | 0;
  if (next < limit && next % 2 === 0) {
    return fibNext(curr, next, next + sum | 0, limit);
  } else if (next < limit) {
    return fibNext(curr, next, sum, limit);
  } else {
    return sum;
  }
}

var fibNext = fib;

console.log(fib(1, 2, 2, 4000000));

exports.fib = fib;
exports.fibNext = fibNext;
/*  Not a pure module */
